### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework3G1#16]
Which classical function are you going to use for your task guys? I saw there is  no any update to your repository.

**Comment by sharmistharanit** [comment]
Yes I have same question?

**Comment by pratibha77118** [comment]
@tirthbha Please check issue section of your group. we are using periodic time function.

**Comment by tirthbha** [comment]
Yeah, we can, but it will be better for us to observe at your repository.
________________________________
