### ISSUE TITLE
Change Commit Message

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework3G1#40]
Hi @yasmensarhan27,
I see the default commit message of Update Algorithm_periodic_time.md in the main repository. So I think It would be better if you change it to some meaningful commit message there. I don't know whether you can change it after merging the file. You can again make compare and pull request to change the commit.

**Comment by reshnashrestha** [comment]
Yes I noticed the same.

**Comment by yasmensarhan27** [comment]
Noted 
thank you
