### ISSUE TITLE
Documentation #pylint

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework3G1#42]
How to run pylint in python script? https://github.com/orgs/ubsuny/teams/cp23-1

**Comment by pratibha77118** [comment]
@reshnashrestha Pylint is mostly used for checking codes, analyzing errors and other issues in a Python code. Here in our homework we are supposed to include the output of pylint in documentation. So we can use pylint in our algorithm code and include the output in documentation.
