### ISSUE TITLE
Pylint

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework3G1#45]
How do you run pylint in python script?

**Comment by pratibha77118** [comment]
@sharmistharanit I think you know about using pylint. I saw your merge request about using pylint in another group?
 If you have time please share it to us too.

**Comment by sharmistharanit** [comment]
I used exact same thing what prof has done in class. 
<img width="515" alt="image" src="https://github.com/ubsuny/23-Homework3G1/assets/143737948/17db07e3-6717-4328-b5f7-6d026d22731e">
If you write ls code, it will give you a directory and you will find your file.
Next use the same code what Prof showed us in class.

**Comment by pratibha77118** [comment]
Thanks @sharmistharanit we are supposed to the output of pylint in documentation.
