### ISSUE TITLE
Own library!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework3G1#46]
@uarif @pratibha77118 @yasmensarhan27 
Is it necessary to make own library for the unit test also?

**Comment by uarif** [comment]
I think if you don't make its own library, it will not be executed.  @tirthbha

**Comment by uarif** [comment]
Are you keeping your unit test code sepearte?

**Comment by uarif** [comment]
I mean it's a separate file, or you are keeping it inside the original cod?

**Comment by pratibha77118** [comment]
@tirthbha  could you make it more clear what exactly mean making seperate library for unit test?

**Comment by tirthbha** [comment]
@uarif  No this is not for the unit test this one is just for the original code. However, you can do for the unit test in the similar way.

**Comment by tirthbha** [comment]
@uarif I have made for your code so its your library not mine. My library is different

**Comment by tirthbha** [comment]
> @tirthbha could you make it more clear what exactly mean making seperate library for unit test?

You can see the examples that professor has shared to the second point in the task section of our HW3 for more detail.
