### ISSUE TITLE
Unit_test clarification..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G1#47]
@yasmensarhan27 Hello, As, per my knowledge, the unit test is something, to check whether the code is correct or not, The unit test code, is a different code which checks the original code right? @yasmensarhan27 But as @pratibha77118 says, it's the same code, but we just have to change the input values and see the results.(if that is the case, then how can we be so sure if it works for how many values? I mean we can not check many values by our hand right?) I don't know who is wrong here, @laserlab can you please clarify?

**Comment by pratibha77118** [comment]
@uarif Thank you for creating this as an issue. I might be wrong too. We can clear our confusion from other groups also.

**Comment by uarif** [comment]
Yes @pratibha77118 , I am looking into that, Thank you,

**Comment by uarif** [comment]
Will let you know,... @pratibha77118

**Comment by uarif** [comment]
@pratibha77118 But any way, the way I check the code (IF its working or not) if fine. It means the code is fine, but I am still trying to fix the errors.
