### ISSUE TITLE
HW discussion 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G1#5]
Hi group members, I guess, we should discuss the HW. @yasmensarhan27. 
Also, I couldn't find the other member in this group.

**Comment by pratibha77118** [comment]
I am the other member of this group. Which function are we going to choose for this homework @uarif & @yasmensarhan27.

**Comment by uarif** [comment]
> I am the other member of this group. Which function are we going to choose for this homework @uarif & @yasmensarhan27.

I dont know but when I try to mention you, I cant see your name there,

**Comment by uarif** [comment]
@tirthbha Yes, we will do the time period for a pendulum.

**Comment by uarif** [comment]
> @uarif @pratibha77118 @yasmensarhan27 We (G4) have chosen a function "to find the work done by a body moving with different velocities from point A to E". Have you confirmed your classical function that you are going to use?

Cool.

**Comment by tirthbha** [comment]
That's great
________________________________
