### ISSUE TITLE
Create own library

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework3G1#51]
@uarif @pratibha77118 @yasmensarhan27 
I have created library, to separate algorithm part into its own library (module) file. This is the important one that professor mentioned in the second point of tasks (See in HW3: ubsuny).
The code will appear normal only  in preview mode being created in google colab.

**Comment by reshnashrestha** [comment]
I think group 1 is working on that by themselves.

**Comment by tirthbha** [comment]
> I think group 1 is working on that by themselves.

@reshnashrestha Yeah, It just a suggestion for them.
