### ISSUE TITLE
Unit-test-and the code..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G1#57]
Hello @yasmensarhan27, I made some changes to my unit test code, and now it fails your code, but I know your code is correct if even we check it from our side. I still don't understand the issue well, but what I am going to do is, I will put the new line/s added to the unit test code as "comments" in the code, and I will use the old code, it still gives the results but till now, I am unable to resolve the other issues, I run it through different platforms but still getting the same issue. I guess, if the issue still remains, we can keep the file as it is, because it gives the results anyway.

**Comment by reshnashrestha** [comment]
I tried your unit test code to run in various IDE, I faced the same problem. when I checked it, It said it was good but when I tried to run, it showed some error values.

**Comment by uarif** [comment]
> I tried your unit test code to run in various IDE, I faced the same problem. when I checked it, It said it was good but when I tried to run, it showed some error values.

Yes, The issue is there,.

**Comment by uarif** [comment]
@pratibha77118, If the issue doesn't resolve till the deadline, I guess you can write the same explanation about the unit test in your documentation. You can even put a snapshot of the issue.

**Comment by pratibha77118** [comment]
@uarif we get the explanation from Professor that your and mine understanding of unit test are both correct. So you can do unit test using and mention us about your results in an issue. Also you can pull request for the file you tested. I am almost at the end of documentation. I did pylint but could not get pytest result.

**Comment by pratibha77118** [comment]
@uarif Have a look at your issue of unit_test_clarification.

**Comment by uarif** [comment]
> @uarif Have a look at your issue of unit_test_clarification.

What issue you are talking about?

**Comment by pratibha77118** [comment]
<img width="636" alt="Unit_test_clarification" src="https://github.com/ubsuny/23-Homework3G1/assets/72980895/93fbfe74-a860-451d-87c7-836e1d7abe59">
@uarif I mean the issue about the doubts of unit test. Professor has replied about our unit test confusion.
