### ISSUE TITLE
The other file in the repository?

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G1#58]
@yasmensarhan27 what is there the other file for?, in the repository the "algorithm.py" I guess, we should just put one file. Anything else, if you think important, we can put it in the documentation file, just to avoid confusion in the files.

**Comment by yasmensarhan27** [comment]
I will edit every thing now 
sorry of the inconvenience

I'll create 2 files for the algorithm part 
one will be a module that will be imported in the other one

**Comment by pratibha77118** [comment]
@uarif @yasmensarhan27 
Is it okay if I put the description of code you uploaded earlier in the documentation. What else am I supposed to put in documentation ?
