### ISSUE TITLE
Maintainer...

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G1#6]
Who will be the maintainer of the repository?

**Comment by pratibha77118** [comment]
I was the maintainer of earlier group. So I think @yasmensarhan27 gonna be the maintainer.

**Comment by uarif** [comment]
Okay, So Yasmeen is the maintainer of the group now.

**Comment by yasmensarhan27** [comment]
Yes

**Comment by uarif** [comment]
Yeah 👍🏻
