### ISSUE TITLE
pycodestyle checked your algorithm.py

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G1#66]
I checked your algorithm.py file, it throws out a lot of comments. Do you guys want to fix it accordingly? Just letting you know. 
![image](https://github.com/ubsuny/23-Homework3G1/assets/144289804/837a956c-2e40-4025-9b6a-8db320e5adea)

**Comment by pratibha77118** [comment]
Great! I did it by pylint.
