### ISSUE TITLE
Error: matplotlib does not support generators as input

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework3G1#82]
I generated a list using map(), but now I can't plot it

**Comment by yasmensarhan27** [comment]
having the same here

I got the same error

**Comment by Mosaddeq107** [comment]
If you generated a list using the map() function in Python and you want to plot it, you can use a data visualization library like Matplotlib.

**Comment by AhmedCode99** [comment]
@yasmensarhan27 you can fix this by using list().

https://stackoverflow.com/questions/56904450/runtimeerror-matplotlib-does-not-support-generators-as-input
